ref/ams-configuration.tmpl.md
No review required for this PR as this has been reviewed as part of https://github.com/anbox-cloud/discourse-docs/pull/323
=> Add GL sync swap support

ref/component-versions.md, ref/release-notes.md, ref/roadmap.md
* Version updates
* Roadmap updates
<s>**Pending:** Component versions will be updated closer to the release.</s>
=> Release updates to documentation

exp/web-dashboard.md, howto/manage/web-dashboard.md
- Created explanation topic for web dashboard
- Rearranged some parts of the howto guide for using web dashboard
* As per Daniele's feedback, removed screenshots because dashboard is continuously evolving and screenshots will get outdated very soon.
* The sections on creating, managing and streaming applications will be moved out to the howto topics that exist for applications as part of a [future Jira ticket](https://warthogs.atlassian.net/browse/AC-2132). This rearrangement lays some ground work for moving these sections as is to their destinations.
=> Document web dashboard

.wordlist.txt, explanation/security.md
For both https://warthogs.atlassian.net/browse/AC-2046 and https://warthogs.atlassian.net/browse/AC-2045. This will allows us to complete our documentation objectives towards having a complete and dedicated security topic.
=> Add security measures

tutorial/stream-client.md
Based on the feedback we received. updated the
stream client tutorial to:
* Include information about downloading the Anbox streaming SDK
* Include information about using WebRTC
* Add related links
=> Update stream client tutorial

index.md, reference/component-versions.md, reference/release-notes/release-notes.md, reference/roadmap.md
Update roadmap, component revisions (add a section for 1.21.1 but the versions remain the same), move release notes entry to recent releases.
=> Update versions and roadmap

explanation/applications.md, explanation/images.md, explanation/instances.md, explanation/nodes.md, howto/application/wait.md, index.md
Documenting status and descriptions for image, node, instance and application
=> Document object status

explanation/aaos.md, index.md
I have not elaborated much on VHAL because it is too low level for users to know.
=> Create explanation for AAOS+VHAL

reference/component-versions.md, reference/release-notes/release-notes.md, reference/roadmap.md
Pending component version changes and addition of release notes link
=> Document 1.21.2 release changes

reference/release-notes/1.22.1.md
Confirmations required/pending checks:
=> Create 1.22.1 RN

index.md, reference/component-versions.md, reference/release-notes/release-notes.md, reference/roadmap.md
=> Add 1.22.1 specific updates

reference/release-notes/1.22.2.md
=> Create 1.22.2 release notes

index.md, reference/component-versions.md, reference/release-notes/release-notes.md, reference/roadmap.md
Release updates for 1.22.2, pending tasks:
=> Update release details for 1.22.2

.gitignore
This adds additional patterns to ignore.
=> Update .gitignore contents from starter pack

.custom_wordlist.txt, README.md, contribute/landing.md
Fix a typo and add words to ignore to the custom_wordlist.txt file.
=> Fix spellcheck issues

explanation/application-streaming.md, explanation/clustering.md, explanation/images.md, explanation/instances.md, howto/aar/configure.md, howto/anbox/manage-images.md, howto/anbox/tls-for-appliance.md, howto/android/create-virtual-device.md, howto/application/extend-application.md, howto/application/update-application.md, howto/dashboard/landing.md, howto/install-appliance/install-on-aws.md, howto/install-appliance/install-on-azure.md, howto/install-appliance/install-on-google-cloud.md, howto/stream/exchange-oob-data.md, howto/stream/integrate-virtual-keyboard.md, howto/troubleshoot/troubleshoot-application-creation.md, howto/troubleshoot/view-logs.md, howto/update/upgrade-anbox.md, reference/component-versions.md, reference/deprecation-notices.md, reference/prometheus.md, reference/supported-rendering-resources.md, reference/supported-versions.md, tutorial/getting-started-aaos.md, tutorial/getting-started-dashboard.md, tutorial/getting-started.md, tutorial/installing-appliance.md, tutorial/set-up-stream-client.md
This PR updates/prunes old headings to have a cleaner page level TOC on RTD
=> Update headings to have a clean page-level TOC

.custom_wordlist.txt, howto/update/upgrade-anbox.md, reference/component-versions.md, reference/deprecation-notices.md, reference/release-notes/1.23.0.md, reference/release-notes/release-notes.md, reference/roadmap.md, reference/supported-versions.md
- Create 1.23.0 release notes and link it in necessary topics
- Update release roadmap
- Update component versions
- Update upgrade process with correct versions
- Update release notes landing page with new features
Pending tasks
=> 1.23.0 release notes and updates

howto/android/access-instance.md, reference/release-notes/1.23.0.md, reference/release-notes/release-notes-template.md
- Update links pointing to anbox-cloud.io/docs
- Update release notes template
=> Update links pointing to old URLs

explanation/anbox-security.md, explanation/cryptography/crypto_ams.md, explanation/cryptography/crypto_stream_agent.md, explanation/cryptography/landing.md, explanation/landing.md
- Add a landing page for the section
- Revert topic names to reflect components
- Update toctrees to reflect changes in nav
=> Add cryptography topics to navigation

.custom_wordlist.txt, explanation/cryptography/crypto_dashboard.md
=> add source details for crypto packages

explanation/landing.md, howto/landing.md, reference/deprecation-notices.md, reference/landing.md
Hi @keirthana, please review my changes. I'm still new to open source docs and this is my first attempt to contribute to open source projects, so bear with me if I made some basic mistakes :)
Fixes canonical/open-documentation-academy#133
=> Updating landing pages for How to, Explanation, and Reference sections

reference/network-ports.md
We should document these as they are relevant for the user.
=> feat(ref): add missing internal network ports for appliance

.github/workflows/update-api-specs.yaml
See commit messages for details.
=> Fix API reference update workflow

.github/workflows/generate-command-reference.yml
This PR adds a workflow to automate the generation of AMC command reference topics.
=> Automate command reference content

explanation/production-planning.md
https://warthogs.atlassian.net/browse/WD-15602
=> Add DDoS protection guidelines

custom_conf.py
This commit updates the configuration for  swagger generate to refer to the api reference swagger present locally in the directory.
=> feat(conf): update swagger source to refer to local swagger

reference/component-versions.md, reference/release-notes/1.23.2.md, reference/release-notes/release-notes.md
=> Create 1.23.2 release notes

howto/install-appliance/install-on-aws.md, howto/install-appliance/install-on-azure.md, howto/install-appliance/install-on-google-cloud.md, tutorial/installing-appliance.md
=> Clarify order of installation steps for cloud instances

.custom_wordlist.txt, tutorial/landing.md, tutorial/stream-client.md
This PR adds the stream client tutorial to the documentation.
=> Add streaming tutorial

howto/install-appliance/install-on-aws.md
To provide an end to end flow for the appliance installation workflow on AWS.
=> Clarify AWS installation flow

reference/api-reference/gateway-api.yaml
This restores the `gateway-api.yaml` that was wrongly deleted in PR #222
=> Restore the wrongly deleted API file

explanation/aaos.md, howto/android/custom-vhal.md, howto/android/integrate-hidl.md, howto/android/landing.md
=> feat(howto): document the Anbox VHAL HIDL integration into a VHAL implementation

reference/component-versions.md, reference/release-notes/1.24.1.md, reference/release-notes/release-notes-template.md, reference/release-notes/release-notes.md
This PR contains updates for 1.24.1 release documentation.
Pending items that will be added in the course of review:
=> First draft of 1.24.1 documentation

explanation/landing.md, howto/anbox/landing.md, howto/landing.md, reference/cmd-ref/landing.md, reference/landing.md
This PR updates the landing pages to align with the [exemplar](https://docs.google.com/document/d/1T2aiuVCsF5krBQdqt8Rfaq3gXzhxaypoyetkCSN8RL4/edit?tab=t.0#heading=h.gaoj5xnnne7f) provided. This is one of the documentation objectives for 25.04.
=> Update landing pages to align with exemplar

contribute/anbox-style-guide.md
This PR adds the recent terminology guidelines to the style guide.
Associated Jira ticket: N/A
=> Add terminology guidelines

howto/instance/create-instance.md
Add information about the tabs in the instance details page.
=> feat(instances): add docs for instance details page

howto/instance/create-instance.md
- update create instance details
- targeted for 1.25 release
=> update create instance details

howto/application/create-application.md, howto/application/delete-application.md
Add details for creating and deleting applications and creating instances.
=> update create and delete applications details

howto/landing.md
Fixed the navigation error for upgrade Anbox
Yes
N/A
=> Fix navigation error

explanation/ams.md, howto/application/pass-custom-data.md, howto/instance/create-instance.md, reference/release-notes/1.14.2.md, reference/release-notes/1.17.0.md, reference/release-notes/1.19.0.md, reference/release-notes/1.21.0.md
This PR replaces the obsolete API links with the latest links for AMS and Stream Gateway APIs
n/a
=> Replace API links to latest ones

howto/application/create-application.md
- Added info about how to view more details about a specific application version
[WD-18678](https://warthogs.atlassian.net/browse/WD-18678)
[WD-18678]: https://warthogs.atlassian.net/browse/WD-18678?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add info about versions side panel

.custom_wordlist.txt, howto/application/create-application.md, howto/application/update-application.md
- Updated "Create application" howto page (dashboard tab), to reflect the changes to the application creation form
- Added a dashboard tab to the "Update application" howto page as well, with info about updating an application with the dashboard
[WD-19134](https://warthogs.atlassian.net/browse/WD-19134)
[WD-19134]: …
=> Update application howtos [WD-19134]

explanation/anbox-cloud.md, howto/android/access-instance.md, howto/android/debug-graphics-renderdoc.md, howto/application/stream-application.md, reference/glossary.md, reference/release-notes/1.23.0.md, reference/release-notes/1.25.0.md
* Remove duplicate section target and title
* Clarify Android vs Anbox instance in the section target
=> Polish how to access instance guide

howto/application/create-application.md
=> chore: revert version panel changes

howto/application/create-application.md
- Added details about version panel for next release
=> feat: add version details

scripts/ams_configuration.py
When running `make run`, except for the very first time, an infinite loop runs for every doc change because of the auto-generated `ams-configuration.md` file. The script that generates this file writes the output irrespective of whether there are changes to that particular file or not. This file being generated irrespective of changes triggers sphinx autobuild which
builds again and again causing an infinite loop.
This commit fixes the infinite loop by writing to the `ams-configuration.md` file only if there are changes to it.
Yes
N/A
=> Fix infinite loop when running `make run`

reference/component-versions.md, reference/deprecation-notices.md, reference/release-notes/1.25.1.md, reference/release-notes/release-notes.md
This PR creates the release documentation for 1.25.1
Yes
AC-3171
AC-3164
=> Create 1.25.1 documentation

index.md
This PR updates the home page of the documentation to give a new look and add some relevant links with better prominence.
Yes
N/A
=> Update home page

howto/monitor/landing.md
MicroK8s is fading away and Canonical K8s is ready now for use. Let's use it instead. This adds necessary changes to the documentation and small corrections.
n/a
=> feat(monitor): switch to new Canonical K8s

reference/component-versions.md, reference/release-notes/1.25.2.md, reference/release-notes/release-notes.md, tutorial/create-test-virtual-device.md
This PR will contain the 1.25.2 release updates for documentation
Yes
AC-3175
=> Create 1.25.2 documentation

howto/install/deploy-juju.md, howto/install/deploy-terraform.md, howto/install/landing.md
* Add a new howto guide for terraform.
https://warthogs.atlassian.net/browse/AC-3302
=> docs: add how-to for deploying anbox cloud using terraform

howto/cluster/scale-down.md
Add constraint for scaling down a LXD cluster about how database leader node should not be removed.
Yes
Fixes #331
=> Add constraint for scaling down cluster

explanation/anbox-cloud.md, howto/stream/exchange-oob-data.md, reference/provided-images.md
Update documentation for Android 15 support.
Contributes to [AC-2883](https://warthogs.atlassian.net/browse/AC-2883)
[AC-2883]: https://warthogs.atlassian.net/browse/AC-2883?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Android 15 support v1

reference/release-notes/1.26.1.md
This PR edits the release notes to add a known issue that was found from a regression. This PR also adds a note at the top since we are retroactively editing a release note.
We will also do a public announcement of this edit and the issue. 
Yes
=> Add known issue for release notes

index.md
This is an attempt to rewrite the introduction based on user types and what Anbox Cloud does.
AC-3524
=> Rewrite the introduction to Anbox Cloud

.custom_wordlist.txt, howto/instance/expose-services.md, reference/component-versions.md, reference/release-notes/1.27.0.md, reference/release-notes/release-notes.md
This PR contains 1.27.0 release documentation.
Yes
AC-3418
=> Create 1.27.0 documentation

howto/upgrade/upgrade-appliance.md
This PR updates to the latest version in the upgrade appliance example
N/A
=> Update appliance version

howto/instance/configure-instance.md, howto/instance/index.md, reference/ams-instance-configuration.md, reference/index.md
This documents how to configure individual instances with the available configuration options.
https://warthogs.atlassian.net/browse/AC-3337
=> feat: add instance configuration support

howto/install/deploy-terraform.md, howto/monitor/index.md
=> Use the 1.27 channel by default in the terrform plan and COS stack deployment

.sphinx/spellingcheck.yaml, howto/anbox/control-ams-remotely.md, reference/component-versions.md, reference/release-notes/1.27.1.md, reference/release-notes/release-notes.md
This PR contains the release notes for 1.27.1
Yes
AC-3526
=> Create 1.27.1 documentation

reference/component-versions.md
This PR updates snap revisions from the summary in https://github.com/canonical/ams/actions/runs/17790985340
Yes
AC-3526
=> Update snap revisions

reference/deprecation-notices.md
=> Add deprecation notices for Anbox images(Android 12/Android 13/AAOS 13)

howto/instance/create-instance.md
Updated the "Create an instance" howto with a sentence about the delete protection for an instance.
[WD-27019](https://warthogs.atlassian.net/browse/WD-27019)
[WD-27019]: https://warthogs.atlassian.net/browse/WD-27019?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(howto): add a sentence about delete protection for instances [WD-27019]
