- .wordlist.txt
- reference/anbox-https-api.md
This adds VHAL endpoint documentation to the HTTP API docs based on the current version of the VHAL implementation.
> feat(ref): add VHAL HTTP API documentation

- .wordlist.txt
- howto/port/install-system-app.md
- index.md
- reference/ams-configuration.tmpl.md
- reference/anbox-features.md
- reference/android-features.md
- reference/application-manifest.md
- reference/provided-images.md
This updates the documentation by adding what features are supported/unsupported on AOSP/AAOS.
One link is missing for the Platform SDK API while https://github.com/canonical/anbox-cloud.github.com/pull/1 is not merged.
> List of supported Anbox features depending on image type

- howto/aar/deploy.md
- reference/release-notes/1.21.0.md
This commit adds the instructions to make use of the newly added support for instance profiles in AAR.
> docs(aar): add instructions to use instance profiles with AAR

- howto/anbox/develop-platform.md
- howto/stream/client-side-keyboard.md
- howto/stream/oob-data.md
- reference/release-notes/1.15.0.md
- reference/sdks.md
- tutorial/stream-client.md
As the repositories have been moved to the Canonical organization from the Anbox Cloud organization, we should update the repos links to point to the correct URL.
This was done with a simple search and replace:
```bash
rg 'github.com/anbox-cloud' -l \
| xargs -n1 sed -i 's#github.com/anbox-cloud#github.com/canonical#g'
```
> chore: switch github.com/anbox-cloud links to github.com/canonical

- explanation/ams.md
- explanation/instances.md
- howto/application/userdata.md
- reference/anbox-https-api.md
- reference/release-notes/1.14.2.md
- reference/release-notes/1.17.0.md
- reference/release-notes/1.19.0.md
- reference/sdks.md
- reference/supported-rendering-resources.md
Changes all anbox-cloud.github.io links in the docs to instead use canonical.github.io/anbox-cloud.github.com as the previous website is not online anymore.
This was done through a quick search and replace:
```bash
rg 'anbox-cloud.github.io' -l \
| xargs -n1 sed -i 's#anbox-cloud.github.io#canonical.github.io/anbox-cloud.github.com#g'
```
> fix: update links from anbox-cloud.github.io to canonical.github.io

- reference/ams-configuration.yaml
- scripts/generate-ams-config.py
(Need this PR to test the auto generation of AMS configuration tables)
The deprecated data about AMS config attributes are available in the source but it is not getting generated when being published. This PR is to fix it.
> Fixing AMS config missing deprecated column

- reference/application-manifest.md
The instance type field on the dashboard is renamed to resource type. While we advocate using the resources attribute to define the application resources, we need to clarify the disparity in terminology so that we don't break backward compatibility (`instance-type` attribute is deprecated but still not removed completely and users may still be using the attribute)
> Add note about instance type field name in dashboard

- explanation/resources.md
- reference/amc-command-reference/init.md
- reference/amc-command-reference/launch.md
In the docs, the minimum disk size for containers and VMs was swapped: the minimum disk size for a container is 3GB, but the minimum disk size for a VM is 15GB.
> fix(exp,ref): swap container and vm minimum disk size

- .wordlist.txt
- howto/android/landing.md
- howto/android/odm_vhal.md
- index.md
This covers how to use the ODM partition and an addon to override the Anbox Cloud VHAL implementation with a custom-built one. This doesn't cover how to build such a binary, and that's left to the reader for now.
> feat(howto): add howto use a custom VHAL with Anbox Cloud

- howto/application/stream.md
In addition to [PR 51](https://github.com/canonical/anbox-cloud-docs/pull/51/), the howto guide for streaming applications also needs a update to mention the `--enable-streaming` option available from 1.22.
> Update howto for streaming applications

- howto/update/upgrade-anbox.md
This commit adds the instructions required to enable the new stream attach support to charms for customers upgrading from older versions of anbox-cloud bundle.
> docs(charms): add upgrade instructions to enable stream attach support for charms

- .wordlist.txt
- index.md
- reference/release-notes/1.22.0.md
This is a first draft of 1.22.0 release notes. It still has some pending items to be added/updated but I am creating a pull request to allow more review time.
Pending items - Need more information/clarity on these items, will follow up individually:
Not included - The following items were marked for 1.22.0 but not included in the RN for reasons stated:
- [AC-2370](https://warthogs.atlassian.net/browse/AC-2370) Related to AC-2271 which @adglkh confirmed that more work is required from customer side and hence fix is not complete.
- [AC-2310](https://warthogs.atlassian.net/browse/AC-2310) Work related to creating spec, not required in RN.
- [LP 2044846](https://bugs.launchpad.net/anbox-cloud/+bug/2044846) Still in triaged status
- [LP …
> 1.22.0 release notes

- .wordlist.txt
- howto/install-appliance/azure.md
This PR is to add steps to deploy appliance using the Azure quick start template.
The manual steps are still retained for users who wish to deploy manually but it is added inside an expandable element to make the howto guide appear simple.
> Add steps to use Azure quickstart template

- howto/application/create.md
Added a line for a mandatory field in the `manifest.yaml` file (create application page).
> fix(create-application): add cpus in sample manifest.yaml file

- howto/application/create.md
- howto/application/update.md
Need to update the resource presets on display after fixing the missing `cpus`
field upon application creation
> fix(application): fix the resources presets when showing application details

- howto/update/upgrade-appliance.md
Users need to have the latest appliance version before they can upgrade. To that end, when they update their packages, they should also take this time to upgrade their snaps, to ensure the update goes smoothly.
> feat(howto): add snap refresh to the prerequisites

- reference/android-features.md
Vulkan 1.3 and 64 bit only support are available since 1.22 so we can mark both as supported.
> feat: update Android feature list

- reference/supported-versions.md
It was missed after the 1.21 release to update the supported versions in the reference documentation.
> fix: update supported versions

- .github/workflows/cla.yml
As we declare docs open for contributions through GH (we have started with open docs academy but this will be the case when we move to RTD), we need the CLA check in place so that we can be sure that the contributor has signed the CLA.
> Add CLA check

- reference/ams-configuration.yaml
This adds the format for the value of instance.network_proxy.
Fixes https://bugs.launchpad.net/anbox-cloud/+bug/2072510
> Discourse: Add format for instance.network_proxy

- reference/ams-configuration.md
This adds the format for the value of instance.network_proxy.
Fixes https://bugs.launchpad.net/anbox-cloud/+bug/2072510
> RTD: Add format for instance.network_proxy

- .pre-commit-config.yaml
We no longer need URLs to point to discourse posts.
> Remove outdated discourse links checker pre-commit hook

- reference/glossary.md
The changes in this PR enables us to use a term defined in the glossary anywhere and it will be automatically linked to the glossary definition.
> Update glossary to be able to reuse terms

- custom_conf.py
- reference/supported-codecs.md
The link check is flaky when it comes to checking anchors. It often reports working anchors as broken and is unpredictable.
This PR adds configuration to disable checking the anchors.
> Configure link check to ignore anchors

- contribute/anbox-style-guide.md
- explanation/web-dashboard.md
- howto/android/access-instance.md
- howto/application/create-application.md
- howto/application/delete-application.md
- howto/application/stream-application.md
- howto/instance/create-instance.md
- howto/instance/delete-instance.md
- howto/troubleshoot/troubleshoot-dashboard-issues.md
- tutorial/getting-started-dashboard.md
* As per [feedback from the design team](https://github.com/canonical/anbox-cloud-docs/pull/106#discussion_r1699822293), update all terminology to use 'page' when referring to
the dashboard web pages. This aligns with the
terminology used by the UI team on the dashboard
pages.
* Update the style guide with the terminology guidance
> Updating the terminology used to refer dashboard pages

- howto/install-appliance/install-on-github.md
- howto/install-appliance/landing.md
The Github action provides an easy path to enable the use of the Anbox Cloud Appliance on a Github runner as part of a workflow. This provides an initial howto to explain how to make use of the action.
> feat: explain how to use the github action

- reference/component-versions.md
The versioning scheme changed starting with 1.23.0 and needs to be correctly reflected in the component versions.
> fix(ref): use correct image version for 1.23.0

- .github/CODEOWNERS
This will setup the reviewer list automatically to always include the Anbox team.
> feat(gh): assign ownership to the canonical/anbox team

- reference/component-versions.md
The versioning scheme changed with 1.23.0 and the version is no longer just 1.23.0 but includes a suffix for the git revision.
> fix(ref): use correct version for 1.23.0 snaps

- .github/workflows/update-api-specs.yaml
yq doesn't depend on jq (it should!) so we have to explicitly install it.
> fix(gh): install missing jq tool

- reference/ams-configuration-public.md
- reference/landing.md
This PR creates a copy of the existing AMS configuration file and points the TOC to that duplicate file. 
This helps us in avoiding breaking changes when the automation for generating this file from the latest swagger output is merged.
Once the automation is tested and successful, this PR's changes will be reverted.
> Add duplicate file so that public documentation is not affected

- contribute/landing.md
- index.md
Rename TOC heading to contribute. Add prerequisite for contributing to docs. Include quality checks by listing GitHub actions.
> Improve contributing guide #131

- .github/workflows/update-api-specs.yaml
Yq on jammy has -P for emitting YAMl from JSON but on noble a newer verison of yq used -y for that.
-----
This is the last fix necessary to get the workflow to actually do its job :-)
> fix(gh): use correct yq option on noble

- howto/install/deploy-bare-metal.md
- howto/install/deploy-juju.md
This commit updates the docs for new users to start with juju 3.0 as that is the gold standard to use right with new features being developed as a priority for it.
> docs: update juju tutorial to use version 3.0 instead of 2.9

- .sphinx/spellingcheck.yaml
Because of the way the current outputs are generated for AMS configuration and API reference the spellcheck is flagging terminology from files inside the venv and the automatically generated command reference files.
Until we change the venv directory and fix our CLI help text, we need this exemption in place so that the spellcheck does not fail on other unrelated changes.
> Exempt auto-generated and venv files from spellcheck

- reference/provided-images.md
Adding only AOSP Android 14 images to the list for 1.24.0. AAOS, if supported, will have to be added for 1.24.1.
Decision on [PackageManager](https://developer.android.com/reference/android/content/pm/PackageManager) level feature listing is that we should consider providing a list of features but we will need to set it automatically (maybe using [feature list generator](https://github.com/canonical/anbox/blob/main/src/anbox/android/features_list_generator.cpp)). This needs more research and hence not covered in this PR.
> Add Android 14 images to the supported images list for 1.24

- .wordlist.txt
- howto/stream/enable-client-side-video-upscaling.md
Update `client-side video upscaling` section for multi-pass shader support in streaming SDK.
> Update `client-side video upscaling` for multi-pass shader support

- reference/anbox-features.md
Some features were not listed as unsupported for AAOS, but they are. Fix this by adding them to the table and explaining how it works for AAOS.
> Add more features to the unsupported list for AAOS

- howto/troubleshoot/landing.md
To fix issue #206
@canonical/anbox I validated this in theory but not sure if I can test this command in Appliance because it does not apply to the Appliance version of our deployment. Could one of you confirm or validate?
> Fix juju crashdump command

- howto/troubleshoot/troubleshoot-streaming-issues.md
This was forgotten when the appliance documentation was changed.
> fix(howto): update troubleshooting to newer appliance commands

- .custom_wordlist.txt
- explanation/anbox-cloud.md
- explanation/performance.md
- howto/application/pass-custom-data.md
- howto/install/deploy-juju.md
- howto/stream/enable-client-side-video-upscaling.md
- howto/update/upgrade-anbox.md
- reference/component-versions.md
- reference/deprecation-notices.md
- reference/release-notes/1.24.0.md
- reference/release-notes/release-notes.md
- reference/requirements.md
- tutorial/installing-appliance.md
* Add release notes for 1.24.0
* Update release information
* Add component versions
* Remove 20.04 information
Pending:
> Create 1.24.0 release documentation

- howto/troubleshoot/landing.md
Juju 3 drops support for executing the external plug, which causes
the juju crash-dump command to be incomplete in Juju 3 and results
in the following error:
```
$ juju crashdump
ERROR juju: "crashdump" is not a juju command. See "juju --help".
``
Therefore, use the juju-crashdump command in our documentation to
ensure users can collect logs regardless of the Juju version.
Another issue with the suggested command is that we need to include
the `debug-layer` addon followed by the -a parameter, which denotes
the --addon option.
> fix(troubleshoot): use `juju-crashdump` over `juju crash-dump` command

- howto/stream/exchange-oob-data.md
Provide a complete howto guide for the integration of out-of-band v2
feature into the Android application.
> fix(howto): polish exchange-oob-data page

- howto/anbox/tls-for-appliance.md
I took a test run on the current how-to and had to adjust a few things to make it work after recent changes we did to the appliance.  We miss one bug fix for AMS to make it fully work which will come with 1.24.1 but will be soon in 1.24/beta. Regardless of this we should update the documentation to reflect how TLS should be setup.
> Improve guide for TLS configuration of the appliance

- .github/workflows/update-api-specs.yaml
We need to use `sudo` as the gateway API socket doesn't allow access for unprivileged users. Furthermore we now enable the `pipefail` option to prevent the workflow succeeding while the curl command did not.
> Correctly fetch gateway API spec

- .custom_wordlist.txt
- reference/landing.md
- reference/release-notes/release-notes.md
- reference/security-notices.md
- reference/security-policy.md
Since we have some private source code, this PR adds the policy to the documentation in addition to the `SECURITY.md` file to the public repositories.
> Add security policy to documentation

- reference/component-versions.md
- reference/release-notes/1.23.3.md
- reference/release-notes/release-notes.md
Since this is an unplanned patch release, this PR is targeted directly to the `main` branch.
This PR adds the 1.23.3 release notes and image version.
> Add 1.23.3 release documentation

- tutorial/installing-appliance.md
This is required as the kernel modules and drivers installed during the node setup should be installed in the correct and updated kernel on the machine.
> docs(tutorial): add warning to reboot system before running prepare-node-script

- reference/webrtc-streamer.md
Anbox Cloud has supported the AV1 video encoder for some time. The relevant
options for NVIDIA video encoders apply not only to H.264 but also to AV1.
This change introduces support for NVIDIA AV1 video encoder options in the
WebRTC streamer.
> feat(streamer): add support for NVIDIA AV1 video encoder options in WebRTC streamer

- Makefile
- custom_conf.py
- explanation/production-planning.md
- howto/upgrade/upgrade-anbox.md
- reference/release-notes/release-notes.md
The links from the CLI help text are fixed now. So the link check can be enabled now.
This PR enables the link check target and also fixes some outdated links in the documentation.
Jira ticket number: AC-2973
> Enable link check and fix outdated links

- reference/component-versions.md
- reference/release-notes/1.24.2.md
- reference/release-notes/release-notes.md
This PR contains updates for 1.24.2 release documentation.
Pending tasks:
I don't see any deprecations or removal of functionality for this patch. If there is any, please leave a comment.
---
Jira ticket number: AC-3038
> Create 1.24.2 release documentation

- .sphinx/_static/swagger-override.css
This PR fixes the problem that API documentation that is auto-generated from the swagger spec can be read better in dark mode. The attached screenshots show the difference of how the dark mode looked before and after the fix.
Yes
N/A
> Make dark mode better for API documentation

- custom_conf.py
Adds https://jwt.io to ignore list for link checker
The URL causes a broken link check although the link directs to the correct page. Attempts to mention the browser's user agent so that the server does not mistake requests for bots also failed. Adding to the ignore list is the only option for now.
Yes
Exception as this is a housekeeping PR
N/A
> Add jwt.io to ignore list for link checker

- .custom_wordlist.txt
- howto/application/create-application.md
Added info about the applications details page including the overview & versions section and how to upload to the registry, unpublish and delete a specific application version. 
> feat: add docs for application details page

- explanation/anbox-security.md
This PR updates our security documentation with details about how we store user data.
Yes, the linkchecker fails because of an issue with jwt.io which is an issue on their side rather than a broken link. So for this PR, it has to be treated as a non-blocking check.
AC-3069
> feat(exp): update security documentation

- howto/monitor/landing.md
- reference/api-reference/anbox-https-api.md
- reference/prometheus.md
This provides various updates and adjustments for o11y support in Anbox Cloud next to a how to to explain how a user can access the new metrics endpoint the appliance provides.
We remove information about access to endpoints from the Prometheus reference page as this doesn't really belong in there. Instead we will explain through the how-tos how to access different metrics endpoints.
The charmed version of Anbox Cloud will be covered in a separate PR.
Make …
> Initial updates to document o11y support in Anbox Cloud

- explanation/anbox-security.md
- howto/aar/configure.md
- howto/anbox/control-ams-remotely.md
- howto/install/customize-installation.md
- howto/install/deploy-bare-metal.md
- howto/install/deploy-juju.md
- howto/install/enable-high-availability.md
- howto/upgrade/upgrade-anbox.md
- reference/requirements.md
This PR will fix the recently broken Juju links that don't redirect with the Juju docs moving to RTD.
Yes
N/A
> Fix broken Juju links

- .custom_wordlist.txt
- howto/android/access-instance.md
- howto/application/stream-application.md
- howto/monitor/landing.md
- howto/upgrade/upgrade-anbox.md
- reference/component-versions.md
- reference/deprecation-notices.md
- reference/release-notes/1.25.0.md
- reference/release-notes/release-notes.md
This is a PR for 1.25.0 release documentation. It includes release notes, component versions and any other release related changes to upgrade paths.
<s>- [x] _Upgrade Anbox Cloud_ needs to be edited to include the upgrade instructions for _Upgrade LXD_ (AC-3057)</s>
<s>- [x] _Release notes_ need to be updated once @jat-canonical documents the changes to config attributes for all charms (AC-3026)</s>
Make sure to get at least one review from the …
> Create 1.25.0 documentation

- howto/monitor/landing.md
Both deployment and integration commands were mixed and combined in a single command. 
n/a
> fix(monitor): split deploy and integration command

- reference/deprecation-notices.md
- reference/release-notes/1.25.0.md
Reword kernel deprecation to only include kernels strictly before 6.8. We do support 6.8, we only plan to drop support for older verions.
> Reword kernel deprecation to exclude 6.8

- .github/workflows/generate-command-reference.yml
- .github/workflows/update-api-specs.yaml
- Makefile
- howto/cluster/scale-down.md
- howto/cluster/scale-up.md
- howto/monitor/landing.md
- howto/upgrade/upgrade-anbox.md
- reference/charm-configuration.md
- reference/deprecation-notices.md
- reference/landing.md
- reference/release-notes/1.25.0.md
- tutorial/getting-started.md
Add charming changes for ops charms for 1.25.0
https://warthogs.atlassian.net/browse/AC-3026
> docs: add charm configuration deprecations and updates for ops

- howto/android/access-instance.md
Starting from Anbox Cloud 1.25.1, each session can create up to 5 shares. 
This enforces the limit at the session level. A configurable option for adjusting
this limit may be introduced in a future release.
[Summary of documentation updates]
https://warthogs.atlassian.net/browse/AC-2835
> Limit session shares to a maximum of 5

- .github/workflows/automatic-doc-checks.yml
- .github/workflows/cla.yml
We should never refer to a branch or tag but always an explicit git sha256 revision.
n/a
n/a
> chore: pin all external workflows/actions to git rev

- howto/install/customize-installation.md
- howto/install/deploy-juju.md
- howto/install/enable-high-availability.md
- reference/requirements.md
update docs to clarify Ubuntu noble 24.04 support for charm based
deployment.
Fix AC-2955
> Charm noble support

- howto/android/access-instance.md
Updated the documentation to mention that each share expires
after 12 hours by default.
> Add a context for default expiration time for a share

- howto/install/deploy-juju.md
Add a note about the bundles being architecture dependent and the old overlay not working anymore.
> docs(charms): add note for bundle architectures

- howto/upgrade/upgrade-appliance.md
With 1.26 we introduce a new upgrade-node-script command which a user needs to run to upgrade anything on the host and outside of the snap context.
https://warthogs.atlassian.net/browse/AC-3246
> feat: extend appliance upgrade documentation

- .custom_wordlist.txt
- howto/application/update-application.md
- howto/upgrade/upgrade-anbox.md
- reference/release-notes/1.25.2.md
- reference/release-notes/release-notes.md
This PR clarifies the upgrade documentation to state that we don't officially support any other upgrade than from the n-1 to n upgrade path. This should fix issue #214. 
Yes
AC-3141
> Clarify upgrade documentation

- reference/webrtc-streamer.md
The new field allows to explicitly disable certain video codecs.
https://warthogs.atlassian.net/browse/AC-3314
> feat(ref): add new streamer configuration field for disabled codecs

- howto/monitor/landing.md
This primarily describes how COS can be used for both the appliance and the charmed version of Anbox Cloud and explains how things can be connected.
n/a
> feat(monitor): extend and restructure COS documenation

- reference/requirements.md
The bundles now put haproxy next to the other services so we can save one machine.
https://warthogs.atlassian.net/browse/AC-3329
> feat(ref): adjust charmed deployment requirements

- howto/instance/expose-services.md
- howto/upgrade/upgrade-anbox.md
- reference/deprecation-notices.md
- reference/network-ports.md
1. update the expose-services to cover port-forwarding change in 1.26
2. update the network ports table due to port forwarding changes in 1.26
3. document port forwarding changes in 1.26
3. add deprecation notice for the node controller charm
https://warthogs.atlassian.net/browse/AC-3333
> Update the doc for the service exposure after port forwarding change in 1.26

- explanation/security/charms.md
Cover the topic that guard the sensitive data with Juju secets for charms
AC-3149
> Cover the topic that Juju secrets support in charms

- reference/release-notes/1.26.0.md
Limit security patch level issue to Android 15 only
None
> Limit security patch level issue to Android 15 only

- reference/release-notes/1.26.0.md
This change adds a workaround to the bug 
https://bugs.launchpad.net/anbox-cloud/+bug/2110194
and enable streaming in an insecure way.
Note: we can't not simply replace the incorrect certificate with
the ca certificate by copying it from the anbox-stream-gateway unit
to anbox-cloud-dashboard due to the fact the private IP was not
included into the SAN list when generating the private certificates
for stream-gateway used in the tls verification.
See the following commits for details:
https://github.com/canonical/anbox-cloud-charms/commit/65cc339f89ef57a7a3f5322865e113cbc8f29f73
Hence so far, the easiest way to unblock people from streaming is
to disable TLS verification on the dashboard side.
1. Run `make …
> fix(release-notes): add a workaround to enable streaming in an insecure way

- howto/cluster/scale-down.md
- howto/cluster/scale-up.md
- Avoid scaling up or down a LXD cluster while the LXD leader is
rebooting, unless Juju has elected a new leader.
- Updated scale-down to distinguish between database leader and Juju
leader unit, and emphasized best practices for safe removal of units.
https://warthogs.atlassian.net/browse/AC-3365
> Polish the LXD cluster scale up and down section

- howto/install/deploy-juju.md
fix(howto): remove database leader info from status message
The misleading "Role: Database-leader" message has been removed
from `juju status`, as it was inconsistent with the actual LXD
cluster state and could cause confusion.
[Summary of documentation updates]
https://warthogs.atlassian.net/browse/AC-3365
> fix(howto): remove database leader info from status message

- howto/troubleshoot/troubleshoot-instance-failures.md
This PR adds troubleshooting information for users who fail to attach the Ubuntu Pro token the first time when they initialize the appliance and end with image authentication set as False. 
Yes
N/A
> Add troubleshooting for image authentication

- howto/anbox/control-ams-remotely.md
This PR removes the instructions to expose the AMS HTTPS service.
Yes
N/A
> Remove options to expose the AMS HTTPS service

- reference/network-ports.md
The appliance no longer uses node controller. This PR removes the outdated information in documentation.
Yes
N/A
> Remove node controller ports for appliance

- howto/monitor/landing.md
- howto/upgrade/upgrade-anbox.md
- howto/upgrade/upgrade-appliance.md
Anbox Cloud 1.26 has been released for a while. Hence using the 1.26 , 
which is the latest channel in the upgrade guide.
> Use 1.26 channel for anbox cloud charm on upgrade guide

- .github/workflows/update-api-specs.yaml
In order to keep API documentation in line with what we currently have released we use latest/stable instead of determining the version to use from the (currently incorrect) .base_version file.
n/a
> fix(gh): use latest/stable for appliance installation

- explanation/capacity-planning.md
- howto/cluster/configure-nodes.md
- scripts/ams-configuration.md.j2
This PR clarifies documentation around our GPU slots and GPU encoder slots assignment. The default values documented per GPU vendor will be corrected via https://github.com/canonical/ams/pull/1227
Yes
AC-3466
> Clarify GPU slots usage

- howto/install-appliance/setup-oidc/auth0.md
- howto/install-appliance/setup-oidc/configure-oidc.md
- add audience url for when the access token will be used 
> feat: add docs for audience url while using auth0

- reference/requirements.md
The following PR from anbox-cloud-charms repo
https://github.com/canonical/anbox-cloud-charms/pull/602
was not backported to the 1.26 release series.
Hence update the target release version for the haproxy charm in the upgrade guide.
[Summary of documentation updates]
> fix(reference): reword the upgrade guide for the haproxy charm

- index.md
Based on a review with Daniele and some feedback from Design team too, rearranging the community and project section to truly reflect topics that indicate actions of us helping the community, the community helping us, or us and community working together.
This PR also includes some additions to the "In this documentation" cards and providing a more compact layout.
Make sure to get at least one review from the …
> Rearrange home page grid

- howto/port/install-apk-system-app.md
Add a permission list example for the how to related to installed system apps. I needed to use aam and follow this howto recently, and I wasn't sure what the format for permissions was. This clarifies it greatly by introducing a simple example based on one of our test apps.
Contributes to [AC-3548](https://warthogs.atlassian.net/browse/AC-3548). …
> Add permission example for system app howto

- scripts/ams_configuration.py
This commit removes the dead code to fetch the swagger from a url as we do not use it anymore. We generate the configuration using the swagger present within the repository which is being updated using a workflow.
> refactor: remove fetching swagger from url

- conf.py
This PR excludes the following unnecessary URLs from the sitemap, providing better indexing:
- https://documentation.ubuntu.com/anbox-cloud/genindex/
- https://documentation.ubuntu.com/anbox-cloud/404/
-https://documentation.ubuntu.com/anbox-cloud/search/
Yes
AC-3607
> Exclude 404 and other unwanted URLS from sitemap

- howto/android/access-android-instance.md
Small reword of a dashboard-related section of the "Access an Android instance" how-to, following the recent overhaul to ADB share management in the dashboard.
Note that this should not be merged before the milestone release for ADB share management (which is 1.28).
WD-24633
> fix(howto): update "Access an Android instance" after ADB share overhaul [WD-24633]

- explanation/security/charms.md
Explain that tls issued certificates for etcd must remain isolated to restrict access to AMS.
[Summary of documentation updates]
> Clarify TLS certificate usage for etcd and mTLS

- howto/application/stream-application.md
- howto/instance/create-instance.md
With the recent change in anbox, we now automatically adjust the display
size if a display width or height that is an odd number for proper video encoding.
> Add a note for automatic even size adjustment for display size

- .github/renovate.json
Schedule canonical/create-pull-request action updates on Monday to decrease noise.
N/A
N/A
> Schedule canonical/create-pull-request action updates on monday

- howto/upgrade/upgrade-anbox.md
In the ugprade-anbox charpter, since 1.28 release, we're going to
use NATs charm from 2/stable channel, where comes with features like
- relate with self-signed-certificate TLS charm
- secret support
> Upgrade nats from 2/stable channel
